    schemaVersion: 1.0.0
    locale: en
    title: Static Website Deployment Pipeline Stack

    variableGroups:
    - title: Infrastructure Configuration
      variables:
      - tenancy_ocid
      - release
      - region
      - compartment_ocid
    - title: Source Configuration
      variables:
      - github_url
      - github_secret

    variables:

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visible: true
        title: ${Messages.solutionsHub.solutions.stravaQuickstarts.variables.compartmentTitle()}
        description: ${Messages.solutionsHub.solutions.stravaQuickstarts.variables.compartmentDescription()}

      github_url:
        type: string
        required: true
        visible: true
        title: GitHub repo URL for Function source code

      github_token:
        type: password
        required: true
        visible: true
        title: GitHub personal access token with access to the GitHub repo
