AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Lambda service. State is stored in SimpleDB.
Resources:
  sdbDomain:
    Type: AWS::SDB::Domain
  enviroStore:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}Store"
      Handler: enviroStore.handler
      Runtime: nodejs8.10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 'sdb:PutAttributes'
              Resource: !Sub "arn:aws:sdb:*:*:domain/${sdbDomain}"
      Environment:
        Variables:
          SDB_REGION: !Ref "AWS::Region"
          SDB_DOMAIN: !Ref sdbDomain
  enviroRetrieve:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}Retrieve"
      Handler: enviroRetrieve.handler
      Runtime: nodejs8.10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 'sdb:Select'
              Resource: 'arn:aws:sdb:*:*:*'
      Environment:
        Variables:
          SDB_REGION: !Ref "AWS::Region"
          SDB_DOMAIN: !Ref sdbDomain
  enviroStoreInvokeGroup:
    Type: AWS::IAM::Group
    Properties:
      Policies:
      - PolicyName: !Sub "${AWS::StackName}StoreInvoke"
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: "lambda:InvokeFunction"
            Resource: !GetAtt enviroStore.Arn
          Version: '2012-10-17'
  enviroStoreInvokeGroupMembers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref enviroStoreInvokeGroup
      Users:
        - karel
  enviroRetrieveInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: !Sub "${AWS::StackName}RetrieveInvoke"
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: "lambda:InvokeFunction"
            Resource: !GetAtt enviroRetrieve.Arn
          Version: '2012-10-17'
  enviroRetrieveInvokeIDPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "${AWS::StackName}RetrieveInvokePool"
      AllowUnauthenticatedIdentities: True
  enviroRetrieveInvokeIDRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref enviroRetrieveInvokeIDPool
      Roles:
        unauthenticated : !GetAtt enviroRetrieveInvokeRole.Arn