AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Lambda service. State is stored in SimpleDB.
Resources:

  enviroStore:
    Type: AWS::Serverless::Function
    Properties:
      Handler: enviroStore.handler
      Runtime: nodejs8.10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 'sdb:PutAttributes'
              Resource: 'arn:aws:sdb:*:*:domain/enviro*'
      Environment:
        Variables:
          SDB_REGION:
          SDB_DOMAIN:

  enviroRetrieve:
    Type: AWS::Serverless::Function
    Properties:
      Handler: enviroRetrieve.handler
      Runtime: nodejs8.10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 'sdb:PutAttributes'
              Resource: 'arn:aws:sdb:*:*:domain/enviro*'
      Environment:
        Variables:
          SDB_REGION:
          SDB_DOMAIN: