AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Lambda service. State is stored in SimpleDB.
Resources:
  sdbDomain:
    Type: AWS::SDB::Domain
  enviroStore:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-Store"
      Handler: enviroStore.handler
      Runtime: nodejs8.10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 'sdb:PutAttributes'
              Resource: !Sub "arn:aws:sdb:*:*:domain/${sdbDomain}"
      Environment:
        Variables:
          SDB_REGION: !Ref "AWS::Region"
          SDB_DOMAIN: !Ref sdbDomain
  enviroRetrieve:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-Retrieve"
      Handler: enviroRetrieve.handler
      Runtime: nodejs8.10
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 'sdb:Select'
              Resource: 'arn:aws:sdb:*:*:*'
      Environment:
        Variables:
          SDB_REGION: !Ref "AWS::Region"
          SDB_DOMAIN: !Ref sdbDomain